# <a id='toc1_'></a>[Datenqualität (intern) 📉](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- [Datenqualität (intern) 📉](#toc1_)    
  - [Datenstand 🕥](#toc1_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

<br>

## <a id='toc1_1_'></a>[Datenstand 🕥](#toc0_)

In [1]:
import os
from pathlib import Path
import pandas as pd
import datetime as dt
from pandas_plots import tbl, pls, hlp
import duckdb as ddb

from connection_helper import sql
import numpy as np

hlp.show_package_version(["plotly"])

dir_db=Path("C://temp") if hlp.get_os(hlp.OperatingSystem.WINDOWS) else Path(os.path.expanduser("~/tmp"))

file_epi = dir_db/'2025-06-20_data_epi.duckdb'
file_meta = dir_db/'2025-06-20_meta_epi.duckdb'

if not file_epi.exists() or not file_meta.exists():
    raise Exception(f"files {file_epi} or {file_meta} not found")

URL_V2 = 'https://gitlab.opencode.de/robert-koch-institut/zentrum-fuer-krebsregisterdaten/cancerdata-references/-/raw/main/data/v2/'

os.environ['THEME']='light'

🐍 3.12.8 | 📦 plotly: 6.3.1 | 📦 pandas: 2.3.3 | 📦 numpy: 1.26.4 | 📦 duckdb: 1.4.1 | 📦 pandas-plots: 0.19.1 | 📦 connection-helper: 0.13.1

In [2]:
batch_min=399

In [3]:
sql.print_meta(file_epi)
# print(f"\n{'latest batch:': <25}{batch_max}")

sqlite db file:          2025-06-20_data_epi.duckdb
data tag:                epi2024_2
sql table created:       2025-06-20 15:31:26
document created:        2025-10-09 11:22:09

In [4]:
con = ddb.connect()
con.execute("PRAGMA disable_progress_bar;")
con.execute(f"ATTACH DATABASE '{file_epi}' AS epi (READ_ONLY);")
con.execute(f"ATTACH DATABASE '{file_meta}' AS meta (READ_ONLY); set schema 'epi';")

In [5]:
Batches = con.sql("select * from meta.Batches;")
Checks = con.sql("select * from meta.Checks;")
ColumnCheck = con.sql("select * from meta.ColumnCheck;")
Frequencies = con.sql("select * from meta.Frequencies;")
# _meta_meta = con.sql("select * from meta._meta;")

df_checks = Checks.to_df().astype({"EKRNR": str})
df_freqs = (
    Frequencies.project(
        "*, concat(cast(BatchID as varchar),' | ', cast(cast(BatchZeit as date) as varchar)) as batch_label"
    )
    .to_df()
    .astype({"EKRNR": str})
)
# df_columnchecks= ColumnCheck.to_df().set_index('ColumnCheckID')
# df_checks = df_checks.join(df_columnchecks, on='ColumnCheckID')
# df_checks["check_label"] = df_checks.apply(lambda x: f"{x['Alias']}[{x['ColumnCheckID']}]", axis=1)
# df_checks= df_checks[["EKRNR","Anzahl","BatchID","DJahr","check_label","ColumnCheckID"]]

In [6]:
db_epi = con.sql("select * from Tumor4;").project("*, left(ICDGM10,3) as icd10_3d")

In [ ]:
batch_max=df_checks['BatchID'].max()

(ColumnCheck
    .filter("isTracked and not isInactive")
    .project("ColumnCheckID, Alias, Description")
    .order("Alias")
    .to_df()
    )

,ColumnCheckID,Alias,Description
0,83,A_EKRNR_GKZ_unplausibel,<html>Laut GKZ kommt der Patient nicht aus dem...
1,66,A_ICD10_SEX_fehlerhaft,<html>Männer mit frauentypischen Tumoren (ICD1...
2,54,A_ICD10_keineAuswertung,<html>Die Diagnose ist nicht gemäß ICD-10-WHO ...
3,37,A_Mehrfachmeldung,<html>Die Meldung wurde als Mehrfachmeldung zu...
4,1,A_SEX_fehlerhaft,"<html>Die Variable ""Geschlecht"" ist leer oder ..."
5,58,A_Zeitangaben_fehlerhaft,<html>Entweder Geburts- und/oder Diagnosejahr ...
6,67,B_DALT_HISC_ICD10_unplausibel,<html>Das Diagnosealter passt nicht zur Histol...
7,77,B_DALT_unplausibel,"<html>Unwahrscheinlich hohes Patientenalter, w..."
8,39,B_DCO_DDIMP_inkonsistent,<html>Fälle zum gleichen Patienten mit gleiche...
9,70,B_DIG_HISC_unplausibel,<html>Die Kombination aus Dignität und Histolo...
10,69,B_DIG_ICDO3_unplausibel,<html>Die Kombination aus Lokalisation und Dig...
11,72,B_DSICH_HISC_unplausibel,<html>Die Diagnosesicherung passt nicht zur Hi...
12,82,B_Entscheidung_Mehrfachtumor_unplausibel,<html>Meldungen wurden als unterschiedliche Tu...
13,85,B_GRAD_HISC_unplausibel,<html>Das Grading passt nicht zur Histologie:<...
14,55,B_HISC_ICDO3_unplausibel,<html>Gemäß IARC ist die Kombination aus HISC ...
15,60,B_PatAngaben_inkonsistent,<html>Die Angaben zu Geburts- oder Sterbedatum...
16,78,B_TNMM_GROBST_unplausibel,"<html>M-Stadium = 0 (keine Metastase), aber Gr..."
17,20,B_TNMT_DIG_unplausibel,"<html>Die Tumorausdehnung (T) ist mit ""In-Situ..."
18,76,B_TNMx_ICD10_unplausibel,<html>T = 0<br>N = 0 oder leer<br>M = 0 oder l...
19,12,B_TOD_Ja_Aber_Kein_SJ,"<html>Die Variable ""TOD"" wurde auf ""Ja"" gesetz..."
20,64,C_DIG_korrigiert,"<html>Die Dignität wird korrigiert, wenn die o..."
21,43,C_DJ_korrigiert_aufgrund_DSICH,"<html>Das Diagnosedatum wird korrigiert, wenn ..."
22,56,C_HISC_korrigiert,"<html>Die Histologie wird korrigiert, wenn sie..."
23,80,C_ICD10DREI_korrigiert,"<html>Kennzeichnet die Fälle, bei denen die ur..."
24,52,C_ICDO3_korrigiert,"<html>Kennzeichnet die Fälle, bei denen die ur..."
25,84,C_LOKS_korrigiert,"<html>LOKS wurde auf missing gesetzt, da die A..."
26,14,C_SJ>MaxJahr,<html>SJ liegt weniger als 2 Jahre vor Lieferj...
27,44,C_TNMx_korrigiert,"<html>Die Ausprägungen zu T, N oder/und M pass..."
28,74,C_TOD=1_korrigiert_aufgrund_Sterbeangaben,"<html>Laut Sterbeangaben (AUT, DSICH, SD, ICDT..."

In [9]:
db_checks_all_bl = Checks.filter(f"BatchID >= 390 and ColumnCheckID <> 48").aggregate("ColumnCheckID::text as id, BatchID::text as batch, sum(Anzahl) as Anzahl")

_=pls.plot_stacked_bars(db_checks_all_bl.to_df(), swap = True, renderer="")

In [13]:
tbl.describe_df(Checks.project("* exclude (ID)").to_df(),'checks', fig_cols=5)

🔵 *** df: checks ***
🟣 shape: (331_297, 5)
🟣 duplicates: 85_873
🟠 column stats all (dtype | uniques | missings) [values]
- index [0, 1, 2, 3, 4,]
- EKRNR (int32 | 11 | 0 (0%)) [1, 2, 3, 4, 5,]
- ColumnCheckID (int32 | 34 | 0 (0%)) [1, 12, 14, 20, 37,]
- Anzahl (int32 | 4_347 | 0 (0%)) [1, 2, 3, 4, 5,]
- BatchID (int32 | 141 | 0 (0%)) [73, 95, 119, 128, 132,]
- DJahr (object | 13 | 3_588 (1%)) ['2013', '2014', '2015', '2016', '2017',]
🟠 column stats numeric

column        |    count    |  min   |  lower  |   q25   | median  |   mean    |   q75   |  upper  |      max      |    std     |   cv   |        sum        |  skew  |   kurto
--------------+-------------+--------+---------+---------+---------+-----------+---------+---------+---------------+------------+--------+-------------------+--------+----------
EKRNR         | 331_297.000 |  1.000 |   1.000 |   3.000 |   5.000 |     5.757 |   9.000 |  11.000 |        11.000 |      3.113 |  0.541 |     1_907_412.000 |  0.129 |    -1.179
ColumnCheckID | 331_297.000 |  1.000 |   1.000 |  44.000 |  60.000 |    58.502 |  77.000 |  85.000 |        85.000 |     21.326 |  0.365 |    19_381_646.000 | -0.785 |    -0.020
Anzahl        | 331_297.000 |  1.000 |   1.000 |   5.000 |  25.000 | 3_578.922 | 121.000 | 295.000 | 3_742_032.000 | 68_836.964 | 19.234 | 1_185_686_148.000 | 31.389 | 1_171.053
BatchID       | 331_297.000 | 73.000 | 119.000 | 273.000 | 324.000 |   318.107 | 382.000 | 418.000 |       418.000 |     69.644 |  0.219 |   105_388_028.000 | -0.310 |    -0.968

   EKRNR  ColumnCheckID  Anzahl  BatchID DJahr
0      6             52       7      412   alt
1      5             52       1      412   alt
2      6             52      54      412   alt